server:
  port: '8001'
spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        health-check-interval: 5s

# service-b URL
service:
  b:
    url: http://ms-service-b/service/b

# resilience4j config
resilience4j.circuitbreaker:
configs:
    default:
        registerHealthIndicator: true
        # Failure rate threshold percentage
        failureRateThreshold: 10
        # Minimum number of call attempts before rate threshold percentage is checked.
        ringBufferSizeInClosedState: 10
        # How long to wait until switching to half open.
        waitDurationInOpenState: 3s
        # Number of successful requests before moving back to closed from half open.
        ringBufferSizeInHalfOpenState: 5
        # Exceptions that do not count towards opening the circuit.
        ignoreExceptions:
            # Ignore 4xx exceptions.
            - org.springframework.web.client.HttpClientErrorException
        instances:
            aInformation:
                baseConfig: default

